#!/bin/sh

# [ $# -ge 1 -a -f "$1" ] && input="$1" || input="-"

header_flag=''
while getopts h o
do	case "$o" in
	h)  header_flag=1;;
	[?]) echo >&2 "Usage: $0 [-h] <file> ..."
         exit 1;;
	# [?]) echo >&2 "Usage: $0 [-s] [-d seplist] file ..."
    #      exit 1;;
	esac
done
shift $((OPTIND-1))

if [ $1 ]; then
    input=$1
else
    echo >&2 "Err: No filename is passed."
    echo >&2 "Usage: $0 [-h] <file> ..."
    return
fi

col_format='
   "No.","%m",
   "Time","%t",
   "Source","%s",
   "Destination","%d",
   "Protocol","%p",
   "TTL", "%Cus:ip.ttl:0:R",
   "Length","%L",
   "SrcPort","%S",
   "DstPort","%D",
   "Info","%i"'

header='Number,Time_Epoch,SrcIp,DstIp,ProtocolTTL,FrameLen,SrcPrt,DstPrt,Info...'

if [ $header_flag ]; then echo $header; fi

tshark -r $input -t e -Y "ip" \
    -o "gui.column.format: $col_format" \
    | sed -r 's/^ +//' \
    | sed -r 's/→/ /g' \
    | sed -r 's/[\t ]+/,/g'
#| sed -r 's/^ +//' \             omit initial spaces
#| sed -r 's/→/ /g' \            replace arrow character with blanks
#| sed -r 's/[[:blank:]]+/,/g'   replace sequence of blank characters with comma

# sleep 4

# tshark -r $file -E header=y -E separator=, -t e \
    # -Y "ip" \
    # -T fields \
    # -e frame.number \
    # -e frame.time_epoch \
    # -e ip.src \
    # -e ip.dst \
    # -e _ws.col.Protocol \
    # -e _ws.col.SrcPort \
    # -e _ws.col.DstPort \
    # -e frame.len 
